/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Content struct {
	ExtensionAttributes map[string]map[string]interface{} `json:"extensionAttributes,omitempty"`
	Value []map[string]interface{} `json:"value,omitempty"`
	Lang string `json:"lang,omitempty"`
	Base string `json:"base,omitempty"`
	Src string `json:"src,omitempty"`
	Type string `json:"type,omitempty"`
}
