/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

// DTO representing an owner/organization
type OwnerDto struct {
	Created time.Time `json:"created,omitempty"`
	Updated time.Time `json:"updated,omitempty"`
	Id string `json:"id,omitempty"`
	Key string `json:"key,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	ParentOwner NestedOwnerDto `json:"parentOwner,omitempty"`
	ContentPrefix string `json:"contentPrefix,omitempty"`
	DefaultServiceLevel string `json:"defaultServiceLevel,omitempty"`
	UpstreamConsumer UpstreamConsumerDto `json:"upstreamConsumer,omitempty"`
	LogLevel string `json:"logLevel,omitempty"`
	AutobindDisabled bool `json:"autobindDisabled,omitempty"`
	ContentAccessMode string `json:"contentAccessMode,omitempty"`
	ContentAccessModeList string `json:"contentAccessModeList,omitempty"`
	LastRefreshed time.Time `json:"lastRefreshed,omitempty"`
	Href string `json:"href,omitempty"`
}
