/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

type ImportRecord struct {
	Created time.Time `json:"created,omitempty"`
	Updated time.Time `json:"updated,omitempty"`
	Id Serializable `json:"id"`
	Status string `json:"status,omitempty"`
	StatusMessage string `json:"statusMessage,omitempty"`
	FileName string `json:"fileName,omitempty"`
	GeneratedBy string `json:"generatedBy,omitempty"`
	GeneratedDate time.Time `json:"generatedDate,omitempty"`
	UpstreamConsumer ImportUpstreamConsumer `json:"upstreamConsumer,omitempty"`
}
