/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type MultipartInput struct {
	Preamble string `json:"preamble,omitempty"`
	Parts []InputPart `json:"parts,omitempty"`
}
