/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

type Product struct {
	Created time.Time `json:"created,omitempty"`
	Updated time.Time `json:"updated,omitempty"`
	Uuid string `json:"uuid"`
	Id string `json:"id"`
	Name string `json:"name"`
	Multiplier int64 `json:"multiplier,omitempty"`
	Attributes map[string]string `json:"attributes,omitempty"`
	ProductContent []ProductContent `json:"productContent,omitempty"`
	DependentProductIds []string `json:"dependentProductIds,omitempty"`
	Href string `json:"href,omitempty"`
}
