/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

// DTO representing a Cdn
type CdnDto struct {
	Created time.Time `json:"created,omitempty"`
	Updated time.Time `json:"updated,omitempty"`
	Id string `json:"id,omitempty"`
	Label string `json:"label,omitempty"`
	Name string `json:"name,omitempty"`
	Url string `json:"url,omitempty"`
	Certificate CertificateDto `json:"certificate,omitempty"`
}
