/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ProductContentData struct {
	Content ContentData `json:"content,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
}
