/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

type Environment struct {
	Created time.Time `json:"created,omitempty"`
	Updated time.Time `json:"updated,omitempty"`
	Owner NestedOwner `json:"owner"`
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	Id string `json:"id"`
	EnvironmentContent []EnvironmentContent `json:"environmentContent,omitempty"`
	OwnerId string `json:"ownerId,omitempty"`
}
