/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

// DTO representing a job status
type JobStatusDto struct {
	Created time.Time `json:"created,omitempty"`
	Updated time.Time `json:"updated,omitempty"`
	Id string `json:"id,omitempty"`
	State string `json:"state,omitempty"`
	StartTime time.Time `json:"startTime,omitempty"`
	FinishTime time.Time `json:"finishTime,omitempty"`
	Result string `json:"result,omitempty"`
	PrincipalName string `json:"principalName,omitempty"`
	TargetType string `json:"targetType,omitempty"`
	TargetId string `json:"targetId,omitempty"`
	OwnerId string `json:"ownerId,omitempty"`
	CorrelationId string `json:"correlationId,omitempty"`
	ResultData map[string]interface{} `json:"resultData,omitempty"`
	Done bool `json:"done,omitempty"`
	StatusPath string `json:"statusPath,omitempty"`
	Group string `json:"group,omitempty"`
}
