/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type JobDetail struct {
	JobDataMap map[string]map[string]interface{} `json:"jobDataMap,omitempty"`
	JobBuilder JobBuilder `json:"jobBuilder,omitempty"`
	Durable bool `json:"durable,omitempty"`
	ConcurrentExectionDisallowed bool `json:"concurrentExectionDisallowed,omitempty"`
	PersistJobDataAfterExecution bool `json:"persistJobDataAfterExecution,omitempty"`
	Key JobKey `json:"key,omitempty"`
	Description string `json:"description,omitempty"`
}
