/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

type UpstreamConsumer struct {
	Created time.Time `json:"created,omitempty"`
	Updated time.Time `json:"updated,omitempty"`
	Id string `json:"id"`
	Uuid string `json:"uuid"`
	Name string `json:"name"`
	IdCert IdentityCertificate `json:"idCert,omitempty"`
	Type Consumertype `json:"type"`
	OwnerId string `json:"ownerId"`
	ContentAccessMode string `json:"contentAccessMode,omitempty"`
	WebUrl string `json:"webUrl,omitempty"`
	ApiUrl string `json:"apiUrl,omitempty"`
}
