/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

// DTO representing a certificate serial
type CertificateSerialDto struct {
	Created time.Time `json:"created,omitempty"`
	Updated time.Time `json:"updated,omitempty"`
	Id int64 `json:"id,omitempty"`
	Serial int32 `json:"serial,omitempty"`
	Expiration time.Time `json:"expiration,omitempty"`
	Collected bool `json:"collected,omitempty"`
	Revoked bool `json:"revoked,omitempty"`
}
