/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Generator struct {
	Value string `json:"value,omitempty"`
	Uri string `json:"uri,omitempty"`
	Version string `json:"version,omitempty"`
	Lang string `json:"lang,omitempty"`
	Base string `json:"base,omitempty"`
}
