/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

type Consumer struct {
	Created time.Time `json:"created,omitempty"`
	Updated time.Time `json:"updated,omitempty"`
	Id string `json:"id"`
	Uuid string `json:"uuid"`
	Name string `json:"name"`
	Username string `json:"username,omitempty"`
	EntitlementStatus string `json:"entitlementStatus,omitempty"`
	ServiceLevel string `json:"serviceLevel,omitempty"`
	Role string `json:"role,omitempty"`
	Usage string `json:"usage,omitempty"`
	AddOns []string `json:"addOns,omitempty"`
	SystemPurposeStatus string `json:"systemPurposeStatus,omitempty"`
	ReleaseVer Release `json:"releaseVer,omitempty"`
	IdCert IdentityCertificate `json:"idCert,omitempty"`
	TypeId string `json:"typeId"`
	OwnerId string `json:"ownerId,omitempty"`
	EnvironmentId string `json:"environmentId,omitempty"`
	EntitlementCount int64 `json:"entitlementCount"`
	Facts map[string]string `json:"facts,omitempty"`
	LastCheckin time.Time `json:"lastCheckin,omitempty"`
	InstalledProducts []ConsumerInstalledProduct `json:"installedProducts,omitempty"`
	CanActivate bool `json:"canActivate,omitempty"`
	Capabilities []Consumercapability `json:"capabilities,omitempty"`
	HypervisorId HypervisorId `json:"hypervisorId,omitempty"`
	ContentTags []string `json:"contentTags,omitempty"`
	Autoheal bool `json:"autoheal,omitempty"`
	ContentAccessMode string `json:"contentAccessMode,omitempty"`
	RecipientOwnerKey string `json:"recipientOwnerKey,omitempty"`
	Annotations string `json:"annotations,omitempty"`
	Dev bool `json:"dev,omitempty"`
	Href string `json:"href,omitempty"`
}
