/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

type Entry struct {
	Title string `json:"title,omitempty"`
	Links []Link `json:"links,omitempty"`
	Categories []Category `json:"categories,omitempty"`
	Updated time.Time `json:"updated,omitempty"`
	Id string `json:"id,omitempty"`
	Published time.Time `json:"published,omitempty"`
	Author []Person `json:"author,omitempty"`
	Contributor []Person `json:"contributor,omitempty"`
	Source Source `json:"source,omitempty"`
	Rights string `json:"rights,omitempty"`
	Content Content `json:"content,omitempty"`
	Summary string `json:"summary,omitempty"`
	AnyOther []map[string]interface{} `json:"anyOther,omitempty"`
	ExtensionAttributes map[string]map[string]interface{} `json:"extensionAttributes,omitempty"`
	Lang string `json:"lang,omitempty"`
	Base string `json:"base,omitempty"`
}
