/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type OwnerInfo struct {
	ConsumerCounts map[string]int32 `json:"consumerCounts,omitempty"`
	ConsumerGuestCounts map[string]int32 `json:"consumerGuestCounts,omitempty"`
	EntitlementsConsumedByType map[string]int32 `json:"entitlementsConsumedByType,omitempty"`
	ConsumerTypeCountByPool map[string]int32 `json:"consumerTypeCountByPool,omitempty"`
	EnabledConsumerTypeCountByPool map[string]int32 `json:"enabledConsumerTypeCountByPool,omitempty"`
	ConsumerCountsByComplianceStatus map[string]int32 `json:"consumerCountsByComplianceStatus,omitempty"`
	EntitlementsConsumedByFamily map[string]ConsumptionTypeCounts `json:"entitlementsConsumedByFamily,omitempty"`
}
