/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

type ActivationKey struct {
	Created time.Time `json:"created,omitempty"`
	Updated time.Time `json:"updated,omitempty"`
	Id string `json:"id"`
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	Owner NestedOwner `json:"owner"`
	Pools []ActivationKeyPool `json:"pools,omitempty"`
	Products []Product `json:"products,omitempty"`
	ContentOverrides []ActivationKeyContentOverride `json:"contentOverrides,omitempty"`
	ReleaseVer Release `json:"releaseVer,omitempty"`
	ServiceLevel string `json:"serviceLevel,omitempty"`
	AutoAttach bool `json:"autoAttach,omitempty"`
	OwnerId string `json:"ownerId,omitempty"`
}
