/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

type Subscription struct {
	Created time.Time `json:"created,omitempty"`
	Updated time.Time `json:"updated,omitempty"`
	Id string `json:"id,omitempty"`
	Owner NestedOwner `json:"owner,omitempty"`
	Product ProductData `json:"product,omitempty"`
	DerivedProduct ProductData `json:"derivedProduct,omitempty"`
	ProvidedProducts []ProductData `json:"providedProducts,omitempty"`
	DerivedProvidedProducts []ProductData `json:"derivedProvidedProducts,omitempty"`
	Branding []Branding `json:"branding,omitempty"`
	Quantity int64 `json:"quantity,omitempty"`
	StartDate time.Time `json:"startDate,omitempty"`
	EndDate time.Time `json:"endDate,omitempty"`
	ContractNumber string `json:"contractNumber,omitempty"`
	AccountNumber string `json:"accountNumber,omitempty"`
	Modified time.Time `json:"modified,omitempty"`
	OrderNumber string `json:"orderNumber,omitempty"`
	UpstreamPoolId string `json:"upstreamPoolId,omitempty"`
	UpstreamEntitlementId string `json:"upstreamEntitlementId,omitempty"`
	UpstreamConsumerId string `json:"upstreamConsumerId,omitempty"`
	Cdn Cdn `json:"cdn,omitempty"`
	OwnerId string `json:"ownerId,omitempty"`
	Certificate SubscriptionsCertificate `json:"certificate,omitempty"`
	Stacked bool `json:"stacked,omitempty"`
	StackId string `json:"stackId,omitempty"`
}
