/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// DTO representing an owner/organization
type NestedOwnerDto struct {
	Id string `json:"id,omitempty"`
	Key string `json:"key,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	Href string `json:"href,omitempty"`
}
