/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

// DTO representing an event
type EventDto struct {
	Id string `json:"id,omitempty"`
	TargetName string `json:"targetName,omitempty"`
	Principal PrincipalDataDto `json:"principal,omitempty"`
	Timestamp time.Time `json:"timestamp,omitempty"`
	EntityId string `json:"entityId,omitempty"`
	OwnerId string `json:"ownerId,omitempty"`
	ConsumerUuid string `json:"consumerUuid,omitempty"`
	ReferenceId string `json:"referenceId,omitempty"`
	MessageText string `json:"messageText,omitempty"`
	Type string `json:"type,omitempty"`
	Target string `json:"target,omitempty"`
	ReferenceType string `json:"referenceType,omitempty"`
}
