/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Category struct {
	ExtensionAttributes map[string]map[string]interface{} `json:"extensionAttributes,omitempty"`
	Lang string `json:"lang,omitempty"`
	Base string `json:"base,omitempty"`
	Term string `json:"term,omitempty"`
	Scheme string `json:"scheme,omitempty"`
	Label string `json:"label,omitempty"`
}
