/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

type CertificateSerial struct {
	Created time.Time `json:"created,omitempty"`
	Updated time.Time `json:"updated,omitempty"`
	Id int64 `json:"id"`
	Revoked bool `json:"revoked"`
	Collected bool `json:"collected"`
	Expiration time.Time `json:"expiration,omitempty"`
	Serial int32 `json:"serial,omitempty"`
}
