/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

// DTO representing an entitlement
type EntitlementDto struct {
	Created time.Time `json:"created,omitempty"`
	Updated time.Time `json:"updated,omitempty"`
	Id string `json:"id,omitempty"`
	Consumer NestedConsumerDto `json:"consumer,omitempty"`
	Pool Pool `json:"pool,omitempty"`
	Quantity int32 `json:"quantity,omitempty"`
	Certificates []CertificateDto `json:"certificates,omitempty"`
	StartDate time.Time `json:"startDate,omitempty"`
	EndDate time.Time `json:"endDate,omitempty"`
	Href string `json:"href,omitempty"`
}
