/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

// DTO representing system purpose compliance status
type SystemPurposeComplianceStatusDto struct {
	Status string `json:"status,omitempty"`
	Compliant bool `json:"compliant,omitempty"`
	Date time.Time `json:"date,omitempty"`
	NonCompliantRole string `json:"nonCompliantRole,omitempty"`
	NonCompliantAddOns []string `json:"nonCompliantAddOns,omitempty"`
	NonCompliantSLA string `json:"nonCompliantSLA,omitempty"`
	NonCompliantUsage string `json:"nonCompliantUsage,omitempty"`
	CompliantRole map[string][]EntitlementDto `json:"compliantRole,omitempty"`
	CompliantAddOns map[string][]EntitlementDto `json:"compliantAddOns,omitempty"`
	CompliantSLA map[string][]EntitlementDto `json:"compliantSLA,omitempty"`
	CompliantUsage map[string][]EntitlementDto `json:"compliantUsage,omitempty"`
	NonPreferredSLA map[string][]EntitlementDto `json:"nonPreferredSLA,omitempty"`
	NonPreferredUsage map[string][]EntitlementDto `json:"nonPreferredUsage,omitempty"`
	Reasons []string `json:"reasons,omitempty"`
}
