/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PoolQuantityDto struct {
	Quantity int32 `json:"quantity,omitempty"`
	Pool Pool `json:"pool,omitempty"`
}
