/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Link struct {
	ExtensionAttributes map[string]map[string]interface{} `json:"extensionAttributes,omitempty"`
	Lang string `json:"lang,omitempty"`
	Base string `json:"base,omitempty"`
	Href string `json:"href"`
	Rel string `json:"rel,omitempty"`
	Type MediaType `json:"type,omitempty"`
	Hreflang string `json:"hreflang,omitempty"`
	Title string `json:"title,omitempty"`
	Length string `json:"length,omitempty"`
}
