/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

type DeletedConsumer struct {
	Created time.Time `json:"created,omitempty"`
	Updated time.Time `json:"updated,omitempty"`
	Id string `json:"id"`
	ConsumerUuid string `json:"consumerUuid"`
	OwnerId string `json:"ownerId"`
	OwnerKey string `json:"ownerKey,omitempty"`
	OwnerDisplayName string `json:"ownerDisplayName,omitempty"`
}
