/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

// Version and Status information about running Candlepin server
type Status struct {
	Mode string `json:"mode,omitempty"`
	ModeReason string `json:"modeReason,omitempty"`
	ModeChangeTime time.Time `json:"modeChangeTime,omitempty"`
	Result bool `json:"result,omitempty"`
	Version string `json:"version,omitempty"`
	RulesVersion string `json:"rulesVersion,omitempty"`
	Release string `json:"release,omitempty"`
	Standalone bool `json:"standalone,omitempty"`
	TimeUTC time.Time `json:"timeUTC,omitempty"`
	RulesSource string `json:"rulesSource,omitempty"`
	ManagerCapabilities []string `json:"managerCapabilities,omitempty"`
}
