/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ActivationKeyContentOverrideDto struct {
	ContentLabel string `json:"contentLabel,omitempty"`
	Name string `json:"name,omitempty"`
	Value string `json:"value,omitempty"`
}
