/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

// DTO representing a Pool
type Pool struct {
	Created time.Time `json:"created,omitempty"`
	Updated time.Time `json:"updated,omitempty"`
	Id string `json:"id,omitempty"`
	Type string `json:"type,omitempty"`
	Owner NestedOwnerDto `json:"owner,omitempty"`
	ActiveSubscription bool `json:"activeSubscription,omitempty"`
	CreatedByShare bool `json:"createdByShare,omitempty"`
	HasSharedAncestor bool `json:"hasSharedAncestor,omitempty"`
	SourceEntitlement NestedEntitlementDto `json:"sourceEntitlement,omitempty"`
	Quantity int64 `json:"quantity,omitempty"`
	StartDate time.Time `json:"startDate,omitempty"`
	EndDate time.Time `json:"endDate,omitempty"`
	Attributes map[string]string `json:"attributes,omitempty"`
	RestrictedToUsername string `json:"restrictedToUsername,omitempty"`
	ContractNumber string `json:"contractNumber,omitempty"`
	AccountNumber string `json:"accountNumber,omitempty"`
	OrderNumber string `json:"orderNumber,omitempty"`
	Consumed int64 `json:"consumed,omitempty"`
	Exported int64 `json:"exported,omitempty"`
	Shared int64 `json:"shared,omitempty"`
	Branding []BrandingDto `json:"branding,omitempty"`
	CalculatedAttributes map[string]string `json:"calculatedAttributes,omitempty"`
	UpstreamPoolId string `json:"upstreamPoolId,omitempty"`
	UpstreamEntitlementId string `json:"upstreamEntitlementId,omitempty"`
	UpstreamConsumerId string `json:"upstreamConsumerId,omitempty"`
	ProductName string `json:"productName,omitempty"`
	ProductId string `json:"productId,omitempty"`
	ProductAttributes map[string]string `json:"productAttributes,omitempty"`
	StackId string `json:"stackId,omitempty"`
	Stacked bool `json:"stacked,omitempty"`
	SourceStackId string `json:"sourceStackId,omitempty"`
	DevelopmentPool bool `json:"developmentPool,omitempty"`
	DerivedProductAttributes map[string]string `json:"derivedProductAttributes,omitempty"`
	DerivedProductId string `json:"derivedProductId,omitempty"`
	DerivedProductName string `json:"derivedProductName,omitempty"`
	ProvidedProducts []ProvidedProductDto `json:"providedProducts,omitempty"`
	DerivedProvidedProducts []ProvidedProductDto `json:"derivedProvidedProducts,omitempty"`
	SubscriptionSubKey string `json:"subscriptionSubKey,omitempty"`
	SubscriptionId string `json:"subscriptionId,omitempty"`
	Href string `json:"href,omitempty"`
}
