/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type File struct {
	Path string `json:"path,omitempty"`
	Name string `json:"name,omitempty"`
	Parent string `json:"parent,omitempty"`
	Absolute bool `json:"absolute,omitempty"`
	CanonicalPath string `json:"canonicalPath,omitempty"`
	ParentFile File `json:"parentFile,omitempty"`
	AbsolutePath string `json:"absolutePath,omitempty"`
	AbsoluteFile File `json:"absoluteFile,omitempty"`
	CanonicalFile File `json:"canonicalFile,omitempty"`
	Directory bool `json:"directory,omitempty"`
	File bool `json:"file,omitempty"`
	Hidden bool `json:"hidden,omitempty"`
	TotalSpace int64 `json:"totalSpace,omitempty"`
	FreeSpace int64 `json:"freeSpace,omitempty"`
	UsableSpace int64 `json:"usableSpace,omitempty"`
}
