/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

// DTO representing an upstream consumer
type ConsumerDto struct {
	Created time.Time `json:"created,omitempty"`
	Updated time.Time `json:"updated,omitempty"`
	Id string `json:"id,omitempty"`
	Uuid string `json:"uuid,omitempty"`
	Name string `json:"name,omitempty"`
	Username string `json:"username,omitempty"`
	EntitlementStatus string `json:"entitlementStatus,omitempty"`
	ServiceLevel string `json:"serviceLevel,omitempty"`
	Role string `json:"role,omitempty"`
	Usage string `json:"usage,omitempty"`
	AddOns []string `json:"addOns,omitempty"`
	SystemPurposeStatus string `json:"systemPurposeStatus,omitempty"`
	Owner NestedOwnerDto `json:"owner,omitempty"`
	Environment EnvironmentDto `json:"environment,omitempty"`
	EntitlementCount int64 `json:"entitlementCount,omitempty"`
	Facts map[string]string `json:"facts,omitempty"`
	LastCheckin time.Time `json:"lastCheckin,omitempty"`
	InstalledProducts []ConsumerInstalledProductDto `json:"installedProducts,omitempty"`
	CanActivate bool `json:"canActivate,omitempty"`
	Capabilities []CapabilityDto `json:"capabilities,omitempty"`
	HypervisorId HypervisorIdDto `json:"hypervisorId,omitempty"`
	ContentTags []string `json:"contentTags,omitempty"`
	Autoheal bool `json:"autoheal,omitempty"`
	RecipientOwnerKey string `json:"recipientOwnerKey,omitempty"`
	Annotations string `json:"annotations,omitempty"`
	ContentAccessMode string `json:"contentAccessMode,omitempty"`
	Type ConsumerTypeDto `json:"type,omitempty"`
	IdCert CertificateDto `json:"idCert,omitempty"`
	GuestIds []GuestIdDto `json:"guestIds,omitempty"`
	Href string `json:"href,omitempty"`
	ReleaseVer string `json:"releaseVer,omitempty"`
}
