/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// DTO representing the system purpose attributes available across the set of products belonging to an owner
type SystemPurposeAttributesDto struct {
	Owner NestedOwnerDto `json:"owner,omitempty"`
	SystemPurposeAttributes map[string][]string `json:"systemPurposeAttributes,omitempty"`
}
