/*
 * Candlepin
 *
 * Candlepin is subscription management server written in Java. It helps with management of software subscriptions.
 *
 * API version: 2.3.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

// DTO representing an activation key
type ActivationKeyDto struct {
	Created time.Time `json:"created,omitempty"`
	Updated time.Time `json:"updated,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	Owner NestedOwnerDto `json:"owner,omitempty"`
	ServiceLevel string `json:"serviceLevel,omitempty"`
	AutoAttach bool `json:"autoAttach,omitempty"`
	Pools []ActivationKeyPoolDto `json:"pools,omitempty"`
	ContentOverrides []ActivationKeyContentOverrideDto `json:"contentOverrides,omitempty"`
	Products []string `json:"products,omitempty"`
	ReleaseVer string `json:"releaseVer,omitempty"`
}
